name: rss
description: "用SQlite进行存储的RSS客户端"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  drift: any
  sqlite3_flutter_libs: any
  path_provider: any
  path: any
  google_fonts: any
  xml: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

  # Drift 专属的代码生成器
  drift_dev: any
  # 统一的代码生成自动化工具
  build_runner: any

flutter:
  uses-material-design: true